version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: