import { Types } from 'mongoose';

export const transactionFakeData = (me: string, secondAccount: string) => [
  {
    amount: 50.75,
    currency: 'USD',
    description: 'Initial deposit',
    category: 'Savings',
    accountReceiver: new Types.ObjectId(me),
    accountSender: new Types.ObjectId(secondAccount),
    createdAt: new Date('2025-05-15T10:00:00.000Z'),
  },
  {
    amount: 12.5,
    currency: 'USD',
    description: 'Coffee with friends',
    category: 'Food & Drink',
    accountReceiver: new Types.ObjectId(secondAccount),
    accountSender: new Types.ObjectId(me),
    createdAt: new Date('2025-05-20T14:30:00.000Z'),
  },
  {
    amount: 100.0,
    currency: 'USD',
    description: 'Payment for rent',
    category: 'Bills',
    accountReceiver: new Types.ObjectId(secondAccount),
    accountSender: new Types.ObjectId(me),
    createdAt: new Date('2025-05-01T18:15:00.000Z'),
  },
  {
    amount: 25.99,
    currency: 'USD',
    description: 'Grocery shopping',
    category: 'Groceries',
    accountReceiver: new Types.ObjectId(secondAccount),
    accountSender: new Types.ObjectId(me),
    createdAt: new Date('2025-04-10T09:45:00.000Z'),
  },
  {
    amount: 2000.0,
    currency: 'USD',
    description: 'Salary deposit',
    category: 'Income',
    accountReceiver: new Types.ObjectId(me),
    accountSender: new Types.ObjectId(secondAccount),
    createdAt: new Date('2025-04-25T11:00:00.000Z'),
  },
  {
    amount: 75.0,
    currency: 'USD',
    description: 'Weekend getaway expenses',
    category: 'Travel',
    accountReceiver: new Types.ObjectId(secondAccount),
    accountSender: new Types.ObjectId(me),
    createdAt: new Date('2025-04-24T16:20:00.000Z'),
  },
  {
    amount: 45.0,
    currency: 'USD',
    description: 'Movie night',
    category: 'Entertainment',
    accountReceiver: new Types.ObjectId(secondAccount),
    accountSender: new Types.ObjectId(me),
    createdAt: new Date('2025-05-05T19:30:00.000Z'),
  },
  {
    amount: 89.99,
    currency: 'USD',
    description: 'New headphones',
    category: 'Electronics',
    accountReceiver: new Types.ObjectId(secondAccount),
    accountSender: new Types.ObjectId(me),
    createdAt: new Date('2025-04-15T13:45:00.000Z'),
  },
  {
    amount: 35.5,
    currency: 'USD',
    description: 'Gym membership',
    category: 'Health',
    accountReceiver: new Types.ObjectId(secondAccount),
    accountSender: new Types.ObjectId(me),
    createdAt: new Date('2025-05-01T08:00:00.000Z'),
  },
  {
    amount: 150.0,
    currency: 'USD',
    description: 'Freelance work payment',
    category: 'Income',
    accountReceiver: new Types.ObjectId(me),
    accountSender: new Types.ObjectId(secondAccount),
    createdAt: new Date('2025-04-28T15:20:00.000Z'),
  },
  {
    amount: 29.99,
    currency: 'USD',
    description: 'Online course subscription',
    category: 'Education',
    accountReceiver: new Types.ObjectId(secondAccount),
    accountSender: new Types.ObjectId(me),
    createdAt: new Date('2025-05-10T10:15:00.000Z'),
  },
  {
    amount: 65.0,
    currency: 'USD',
    description: 'Restaurant dinner',
    category: 'Food & Drink',
    accountReceiver: new Types.ObjectId(secondAccount),
    accountSender: new Types.ObjectId(me),
    createdAt: new Date('2025-05-08T20:00:00.000Z'),
  },
  {
    amount: 120.0,
    currency: 'USD',
    description: 'Utility bills',
    category: 'Bills',
    accountReceiver: new Types.ObjectId(secondAccount),
    accountSender: new Types.ObjectId(me),
    createdAt: new Date('2025-03-05T09:00:00.000Z'),
  },
  {
    amount: 40.0,
    currency: 'USD',
    description: 'Haircut and styling',
    category: 'Personal Care',
    accountReceiver: new Types.ObjectId(secondAccount),
    accountSender: new Types.ObjectId(me),
    createdAt: new Date('2025-05-12T14:00:00.000Z'),
  },
  {
    amount: 1800.0,
    currency: 'USD',
    description: 'Monthly salary',
    category: 'Income',
    accountReceiver: new Types.ObjectId(me),
    accountSender: new Types.ObjectId(secondAccount),
    createdAt: new Date('2025-05-01T09:00:00.000Z'),
  },
];
